export { default as catchError } from './catchError'
export { default as delay } from './delay'
export { default as getDomain } from './getDomain'
export { default as API } from './api'
export { default as feathers } from './feathers'
